- name: Set Eth peer Macs of "{{ network.name }}"
  set_fact:
    ethpeer_maclist: "{{ ethpeer_maclist | default([]) + [ network.mac[item|int-1] ] }}"
  with_sequence: start=1 count={{ network.count |default('1')|int }} 
